### ISSUE TITLE
Allow advanced object usage in e-mail template

### ISSUE THREAD

**Issue by nilsenpaul** [xodigital/Formerly#49]
In my e-mail template, I would like (for instance) this to be possible:

    {assetFieldHandle.first().url}

It's not possible now, because of this line (SubmissionService, line 240):

    if ($q->handle == $formHandle . '_' . $a) {

I've changed it locally to this:

    if (strstr($formHandle . '_' . $a, $q->handle)) {

That works.

**Comment by wiso1234** [comment]
Hi,

Thanks for that, I hadn't realised my change to check for bad tags stopped object usage. We needed to add that because heaps of people (including me) kept getting stuck with bad tags in the email and getting an obscure error which didn't give you any clue as to why it was crashing.

Your solution is a good compromise, it should still find most bad tags

thanks for the update, we'll put it in the next push
